name: pamod
channels:
  - defaults
  - conda-forge
  - gurobi
dependencies:
  - python=3.9
  - geopandas
  - matplotlib
  - networkx
  - gurobi
  - pathos
  - jupyter
  - pyarrow
  - requests
  - pyomo
